#!/bin/bash

function reportit() {
	if [[ "$1" == "$2" ]]; then
		echo "ok: $1"
	else
		printf "fail:\n\texpected '$2'\n\tgot '$1'\n"
	fi
}

function testit() {
	declare -a ourary
	declare -a theirary

	while read -r line; do
		ourary+=("$line")
	done < <(./42sh $1)

	while read -r line2; do
		theirary+=("$line2")
	done < <(eval "$1")

	oursjoined=$( IFS=, ; echo "${ourary[*]}" )
	theirsjoined=$( IFS=, ; echo "${theirary[*]}" )

	reportit "$oursjoined" "$theirsjoined"
}

function testem() {
	testit "echo hello world";
	testit "echo hello world | tr a-z A-Z";
	testit "echo hw | grep nope && echo no || echo yes"
	testit "echo a && echo b && echo c || echo d || echo e && echo f"
	testit "echo hw 2>&1 >afile; cat afile"
};

testem
